### PR TITLE
Run commands through `exec` on POSIX compliant OS to avoid zombie procceses.

### PR DESCRIPTION
**Pull request by jails**
It solves the following issue https://github.com/peridot-php/webdriver-manager/issues/11 by using a trick posted in the last comment of https://bugs.php.net/bug.php?id=39992

### CODE REVIEW

**Comment by jails** [comment]
The second commit it not related to that PR but was necessary to make tests to pass (looks like chrome driver binaries now ended up by `.exe` on Win32/64).

**Comment by ezzatron** [comment]
Awesome, thanks for the PR!

**Comment by ezzatron** [comment]
Should be available shortly as [1.3.1](https://github.com/peridot-php/webdriver-manager/releases/1.3.1).

**Comment by jails** [comment]
Awesome :100: !

**Pull request merged**
